# Generated by Django 4.1.3 on 2022-12-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0002_alter_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.JSONField(verbose_name='{}'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favAuctions',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='winnedAuction',
            field=models.JSONField(default='{}'),
        ),
    ]
