# Generated by Django 4.1.3 on 2023-01-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0004_rename_favauctions_profile_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='price',
            new_name='finalPrice',
        ),
        migrations.AddField(
            model_name='auction',
            name='initPrice',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchList',
            field=models.JSONField(default='[]'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='winnedAuction',
            field=models.JSONField(default='[]'),
        ),
    ]
