# Generated by Django 4.1.3 on 2023-01-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0005_rename_price_auction_finalprice_auction_initprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctionId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ethTx',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='auction',
            name='finalPrice',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='auction',
            name='initPrice',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.TextField(default=None),
        ),
    ]
