# Generated by Django 4.1.3 on 2023-01-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0006_alter_auction_auctionid_alter_auction_ethtx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='finalPrice',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(default='not payed', max_length=16),
        ),
    ]
