# Generated by Django 4.1.3 on 2023-01-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0008_auction_auction_start_alter_auction_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='auction_start',
            new_name='start',
        ),
    ]
