# Generated by Django 4.1.3 on 2023-01-19 10:29

from django.db import migrations, models
import micromobility.models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0009_rename_auction_start_auction_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='winnedAuction',
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(micromobility.models.get_sentinel_user), to='micromobility.profile'),
        ),
    ]
