# Generated by Django 4.1.3 on 2023-01-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0010_remove_profile_winnedauction_alter_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctionId',
            field=models.IntegerField(default=0),
        ),
    ]
