# Generated by Django 4.1.3 on 2023-01-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0012_alter_auction_auctionid_alter_auction_ethtx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('c', 'CLOSE'), ('o', 'OPEN')], default='o', max_length=32),
        ),
    ]
