# Generated by Django 4.1.3 on 2023-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0013_alter_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
