# Generated by Django 4.1.3 on 2023-01-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micromobility', '0014_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.CharField(choices=[('powered standing scooter', 'powered_standing_scooter'), ('powered bicycle', 'powered_bicycle'), ('powered seated_scooter', 'powered_seated_scooter'), ('powered self-balacing_board', 'powered_self-balacing_board'), ('powered non-self-balancing_board', 'powered_non-self-balancing_board'), ('powered skates', 'powered_Skates')], default=None, max_length=32),
        ),
    ]
